-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgTboWXBjNE7f4t9ri
YwNzzVdoWL4IeN1SkqAPLXAUTnegCgYIKoZIzj0DAQehRANCAASWddUG4kz6YAat
ybIDzqsJKAE/Sb3QtUm/bbFRw8JaE5/SPTywcz9SsR2c/Jge8zxWdHBlT8A/JSy2
NtARSXxN
-----END PRIVATE KEY-----